In [1]:
run pipeline.py

/Users/arianisfeld/anaconda2/envs/py36/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/Users/arianisfeld/anaconda2/envs/py36/lib/python3.6/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated since IPython 4.0. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
/Users/arianisfeld/anaconda2/envs/py36/lib/python3.6/site-packages/sklearn/grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)

Shape:
 (1274, 48)

Data types:
 CDSCode                                                         object
NCESCode                                                        object
closeddate                                                      object
opendate                                                        object
zip                                                             object
fundingtype                                                     object
soctype                                                         object
eilname                                                         object
gsoffered                                                       object
latitude                                                       float64
longitude                                                      float64
school_level_code_public_school_2012-13                         object
school_level_code_public_school_2011-12                         object
school_level_code_public_school_2010-11                         object
total_students_all_grades_excludes_ae_public_school_2012-13    float64
total_students_all_grades_excludes_ae_public_school_2011-12    float64
total_students_all_grades_excludes_ae_public_school_2010-11    float64
free_and_reduced_lunch_students_public_school_2012-13          float64
free_and_reduced_lunch_students_public_school_2011-12           object
free_and_reduced_lunch_students_public_school_2010-11          float64
male_students_public_school_2012-13                            float64
male_students_public_school_2011-12                            float64
male_students_public_school_2010-11                            float64
female_students_public_school_2012-13                          float64
female_students_public_school_2011-12                          float64
female_students_public_school_2010-11                          float64
hispanic_students_public_school_2012-13                        float64
hispanic_students_public_school_2011-12                        float64
hispanic_students_public_school_2010-11                        float64
black_students_public_school_2012-13                           float64
black_students_public_school_2011-12                           float64
black_students_public_school_2010-11                           float64
white_students_public_school_2012-13                           float64
white_students_public_school_2011-12                           float64
white_students_public_school_2010-11                           float64
asian_or_pacific_islander_students_public_school_2012-13       float64
asian_or_pacific_islander_students_public_school_2011-12       float64
asian_or_pacific_islander_students_public_school_2010-11       float64
full-time_equivalent_fte_teachers_public_school_2012-13        float64
full-time_equivalent_fte_teachers_public_school_2011-12        float64
full-time_equivalent_fte_teachers_public_school_2010-11         object
pupil_teacher_ratio_2012-13                                    float64
pupil_teacher_ratio_2011-12                                    float64
charter_authorizer                                              object
afilliated_organization                                         object
site_type                                                       object
start_type                                                      object
located_within_district                                         object
dtype: object

Summary statistics:
           latitude    longitude  \
count  1271.000000  1271.000000
mean     35.932584  -119.773504
std       2.273723     2.004701
min      32.570376  -124.211440
25%      34.024154  -121.806990
50%      34.740422  -119.062750
75%      37.846086  -118.248075
max      41.772906  -115.570250

       total_students_all_grades_excludes_ae_public_school_2012-13  \
count                                        1002.000000
mean                                          467.423154
std                                           512.125097
min                                             2.000000
25%                                           198.250000
50%                                           344.500000
75%                                           554.750000
max                                          5548.000000

       total_students_all_grades_excludes_ae_public_school_2011-12  \
count                                         935.000000
mean                                          459.658824
std                                           520.835768
min                                             2.000000
25%                                           192.000000
50%                                           338.000000
75%                                           524.000000
max                                          5423.000000

       total_students_all_grades_excludes_ae_public_school_2010-11  \
count                                         850.000000
mean                                          454.955294
std                                           518.518253
min                                             0.000000
25%                                           191.000000
50%                                           331.500000
75%                                           517.250000
max                                          4600.000000

       free_and_reduced_lunch_students_public_school_2012-13  \
count                                         997.000000
mean                                          255.463390
std                                           302.512059
min                                             0.000000
25%                                            67.000000
50%                                           170.000000
75%                                           328.000000
max                                          2440.000000

       free_and_reduced_lunch_students_public_school_2010-11  \
count                                         836.000000
mean                                          202.797847
std                                           290.678778
min                                             0.000000
25%                                            21.000000
50%                                           121.500000
75%                                           275.000000
max                                          2886.000000

       male_students_public_school_2012-13  \
count                          1002.000000
mean                            232.518962
std                             254.332159
min                               0.000000
25%                             100.000000
50%                             169.000000
75%                             273.000000
max                            2750.000000

       male_students_public_school_2011-12  \
count                           934.000000
mean                            228.714133
std                             258.511102
min                               0.000000
25%                              98.000000
50%                             167.000000
75%                             264.750000
max                            2682.000000

       male_students_public_school_2010-11             ...               \
count                           839.000000             ...
mean                            226.302741             ...
std                             260.337680             ...
min                               0.000000             ...
25%                              96.000000             ...
50%                             163.000000             ...
75%                             252.500000             ...
max                            2284.000000             ...

       white_students_public_school_2012-13  \
count                           1002.000000
mean                             150.799401
std                              262.473961
min                                0.000000
25%                                7.000000
50%                               61.000000
75%                              180.250000
max                             2945.000000

       white_students_public_school_2011-12  \
count                            934.000000
mean                             151.229122
std                              259.358759
min                                0.000000
25%                                8.000000
50%                               63.500000
75%                              182.750000
max                             2811.000000

       white_students_public_school_2010-11  \
count                            839.000000
mean                             155.702026
std                              256.362939
min                                0.000000
25%                                8.000000
50%                               71.000000
75%                              205.000000
max                             2537.000000

       asian_or_pacific_islander_students_public_school_2012-13  \
count                                        1002.000000
mean                                           30.669661
std                                            68.796400
min                                             0.000000
25%                                             1.000000
50%                                             7.000000
75%                                            31.000000
max                                          1100.000000

       asian_or_pacific_islander_students_public_school_2011-12  \
count                                         934.000000
mean                                           30.412206
std                                            67.753607
min                                             0.000000
25%                                             1.000000
50%                                             8.000000
75%                                            30.750000
max                                          1066.000000

       asian_or_pacific_islander_students_public_school_2010-11  \
count                                         839.000000
mean                                           29.984505
std                                            68.823690
min                                             0.000000
25%                                             2.000000
50%                                             8.000000
75%                                            29.000000
max                                          1066.000000

       full-time_equivalent_fte_teachers_public_school_2012-13  \
count                                         995.000000
mean                                           20.518663
std                                            23.001424
min                                             0.130000
25%                                             9.000000
50%                                            15.000000
75%                                            23.720000
max                                           275.880000

       full-time_equivalent_fte_teachers_public_school_2011-12  \
count                                         926.000000
mean                                           20.287711
std                                            21.790934
min                                             0.500000
25%                                             8.937500
50%                                            15.000000
75%                                            23.775000
max                                           265.910000

       pupil_teacher_ratio_2012-13  pupil_teacher_ratio_2011-12
count                   992.000000                   921.000000
mean                     23.884063                    23.082562
std                      10.949866                     9.029105
min                       2.000000                     2.000000
25%                      19.750000                    19.650000
50%                      22.615000                    22.210000
75%                      25.235000                    25.210000
max                     206.000000                   150.000000

[8 rows x 29 columns]

Percent null per column:
 CDSCode                                                        0.000000
NCESCode                                                       0.000000
closeddate                                                     0.910518
opendate                                                       0.000000
zip                                                            0.000000
fundingtype                                                    0.007849
soctype                                                        0.000000
eilname                                                        0.000000
gsoffered                                                      0.000000
latitude                                                       0.002355
longitude                                                      0.002355
school_level_code_public_school_2012-13                        0.189168
school_level_code_public_school_2011-12                        0.260597
school_level_code_public_school_2010-11                        0.332810
total_students_all_grades_excludes_ae_public_school_2012-13    0.213501
total_students_all_grades_excludes_ae_public_school_2011-12    0.266091
total_students_all_grades_excludes_ae_public_school_2010-11    0.332810
free_and_reduced_lunch_students_public_school_2012-13          0.217425
free_and_reduced_lunch_students_public_school_2011-12          0.461538
free_and_reduced_lunch_students_public_school_2010-11          0.343799
male_students_public_school_2012-13                            0.213501
male_students_public_school_2011-12                            0.266876
male_students_public_school_2010-11                            0.341444
female_students_public_school_2012-13                          0.213501
female_students_public_school_2011-12                          0.266876
female_students_public_school_2010-11                          0.341444
hispanic_students_public_school_2012-13                        0.213501
hispanic_students_public_school_2011-12                        0.266876
hispanic_students_public_school_2010-11                        0.341444
black_students_public_school_2012-13                           0.213501
black_students_public_school_2011-12                           0.266876
black_students_public_school_2010-11                           0.341444
white_students_public_school_2012-13                           0.213501
white_students_public_school_2011-12                           0.266876
white_students_public_school_2010-11                           0.341444
asian_or_pacific_islander_students_public_school_2012-13       0.213501
asian_or_pacific_islander_students_public_school_2011-12       0.266876
asian_or_pacific_islander_students_public_school_2010-11       0.341444
full-time_equivalent_fte_teachers_public_school_2012-13        0.218995
full-time_equivalent_fte_teachers_public_school_2011-12        0.273155
full-time_equivalent_fte_teachers_public_school_2010-11        1.000000
pupil_teacher_ratio_2012-13                                    0.221350
pupil_teacher_ratio_2011-12                                    0.277080
charter_authorizer                                             0.059655
afilliated_organization                                        0.515699
site_type                                                      0.059655
start_type                                                     0.059655
located_within_district                                        0.059655
dtype: float64

in the if
Index(['CDSCode', 'NCESCode', 'closeddate', 'opendate', 'zip', 'fundingtype',
       'soctype', 'eilname', 'gsoffered', 'latitude', 'longitude',
       'school_level_code_public_school_2012-13',
       'school_level_code_public_school_2011-12',
       'school_level_code_public_school_2010-11',
       'total_students_all_grades_excludes_ae_public_school_2012-13',
       'total_students_all_grades_excludes_ae_public_school_2011-12',
       'total_students_all_grades_excludes_ae_public_school_2010-11',
       'free_and_reduced_lunch_students_public_school_2012-13',
       'free_and_reduced_lunch_students_public_school_2011-12',
       'free_and_reduced_lunch_students_public_school_2010-11',
       'male_students_public_school_2012-13',
       'male_students_public_school_2011-12',
       'male_students_public_school_2010-11',
       'female_students_public_school_2012-13',
       'female_students_public_school_2011-12',
       'female_students_public_school_2010-11',
       'hispanic_students_public_school_2012-13',
       'hispanic_students_public_school_2011-12',
       'hispanic_students_public_school_2010-11',
       'black_students_public_school_2012-13',
       'black_students_public_school_2011-12',
       'black_students_public_school_2010-11',
       'white_students_public_school_2012-13',
       'white_students_public_school_2011-12',
       'white_students_public_school_2010-11',
       'asian_or_pacific_islander_students_public_school_2012-13',
       'asian_or_pacific_islander_students_public_school_2011-12',
       'asian_or_pacific_islander_students_public_school_2010-11',
       'full-time_equivalent_fte_teachers_public_school_2012-13',
       'full-time_equivalent_fte_teachers_public_school_2011-12',
       'full-time_equivalent_fte_teachers_public_school_2010-11',
       'pupil_teacher_ratio_2012-13', 'pupil_teacher_ratio_2011-12',
       'charter_authorizer', 'afilliated_organization', 'site_type',
       'start_type', 'located_within_district', 'closedyear', 'closed_2002.0',
       'closed_2012.0', 'closed_2013.0', 'closed_2014.0', 'closed_2015.0',
       'closed_2016.0', 'closed_2017.0', 'closed_nan'],
      dtype='object')
GB
{'learning_rate': 0.1, 'max_depth': 1, 'n_estimators': 1, 'subsample': 0.5}
RF
{'max_depth': 1, 'max_features': 'sqrt', 'min_samples_split': 10, 'n_estimators': 1}
DT
{'criterion': 'gini', 'max_depth': 1, 'max_features': 'sqrt', 'min_samples_split': 10}
KNN
{'algorithm': 'auto', 'n_neighbors': 5, 'weights': 'uniform'}
LR
{'C': 0.01, 'penalty': 'l1'}
NB
{}

In [3]:
results

,model_type,clf,parameters,auc-roc,precision_5,accuracy_5,recall_5,precision_10,accuracy_10,recall_10,precision_20,accuracy_20,recall_20,runtime,y_pred_probs
0,GB,([DecisionTreeRegressor(criterion='friedman_ms...,"{'learning_rate': 0.1, 'max_depth': 1, 'n_esti...",0.500000,0.166667,0.960784,1.0,0.08,0.909804,1.0,0.039216,0.807843,1.0,0.008975,"[0.0289775563713, 0.0289775563713, 0.028977556..."
1,RF,"(DecisionTreeClassifier(class_weight=None, cri...","{'max_depth': 1, 'max_features': 'sqrt', 'min_...",0.500000,0.166667,0.960784,1.0,0.08,0.909804,1.0,0.039216,0.807843,1.0,0.108218,"[0.030602171767, 0.030602171767, 0.03060217176..."
2,DT,"DecisionTreeClassifier(class_weight=None, crit...","{'criterion': 'gini', 'max_depth': 1, 'max_fea...",0.500000,0.166667,0.960784,1.0,0.08,0.909804,1.0,0.039216,0.807843,1.0,0.001328,"[0.0256916996047, 0.0256916996047, 0.025691699..."
3,KNN,"KNeighborsClassifier(algorithm='auto', leaf_si...","{'algorithm': 'auto', 'n_neighbors': 5, 'weigh...",0.726285,0.083333,0.952941,0.5,0.08,0.909804,1.0,0.039216,0.807843,1.0,0.010063,"[0.2, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.2, 0.0, ..."
4,LR,"LogisticRegression(C=0.01, class_weight=None, ...","{'C': 0.01, 'penalty': 'l1'}",0.500000,0.166667,0.960784,1.0,0.08,0.909804,1.0,0.039216,0.807843,1.0,0.085134,"[0.126597499002, 0.126597499002, 0.12659749900..."
5,NB,GaussianNB(priors=None),{},0.691700,0.083333,0.952941,0.5,0.04,0.901961,0.5,0.019608,0.800000,0.5,0.001353,"[0.00106277048924, 0.00185301044796, 0.0001337..."

In [4]:
from sklearn.preprocessing import LabelEncoder

In [7]:
le = preprocessing.LabelEncoder()
le.fit(df.fundingtype)

TypeError: '>' not supported between instances of 'str' and 'NoneType'

In [14]:
import util as u
u.check_nulls( df, "charter_authorizer")

def replace_nones(df, cols, rep="None"):
    '''replace None types with rep (string)'''
    for col in cols:
        df.ix[:,df.ix[:,col].isnull()] = df.ix[:,df.ix[:,col].isnull()]

,CDSCode,NCESCode,closeddate,opendate,zip,fundingtype,soctype,eilname,gsoffered,latitude,...,full-time_equivalent_fte_teachers_public_school_2011-12,full-time_equivalent_fte_teachers_public_school_2010-11,pupil_teacher_ratio_2012-13,pupil_teacher_ratio_2011-12,charter_authorizer,afilliated_organization,site_type,start_type,located_within_district,closedyear
11,10621660115196,61455011900,2015-03-06,2009-08-17,93721,Directly funded,High Schools (Public),High School,9-12,36.731908,...,6.50,None,17.33,20.15,None,None,None,None,None,2015.0
15,10621661030667,61455007962,2013-06-20,1999-07-01,93706-3117,Directly funded,High Schools (Public),High School,7-12,36.727632,...,8.00,None,22.77,30.25,None,None,None,None,None,2013.0
36,10767780122770,60141512704,2014-06-30,2010-08-16,93706,Directly funded,Elementary Schools (Public),Elementary,K-8,36.714339,...,5.00,None,19.23,19.40,None,None,None,None,None,2014.0
38,1100170109835,69105110546,2015-07-31,2005-08-29,94560-5359,Directly funded,K-12 Schools (Public),Elementary-High Combination,K-12,37.521436,...,63.00,None,21.29,25.29,None,None,None,None,None,2015.0
40,1100170118489,69105112283,2015-06-30,2008-08-21,94703-1414,Directly funded,High Schools (Public),High School,9-12,37.868991,...,19.33,None,21.67,21.31,None,None,None,None,None,2015.0
69,14101400121301,69101112555,2015-07-16,2010-07-01,90015-3582,Locally funded,High Schools (Public),High School,9-12,34.031953,...,21.00,None,30.89,34.48,None,None,None,None,None,2015.0
82,15637680124842,63633012850,2014-06-30,2011-09-06,90245,Directly funded,K-12 Schools (Public),Elementary-High Combination,K-12,33.903276,...,11.51,None,32.24,27.54,None,None,None,None,None,2014.0
83,15638260127258,63888013102,2014-09-30,2013-08-12,93561,Directly funded,K-12 Schools (Public),Intermediate/Middle/Junior High,6-12,35.132188,...,NaN,None,NaN,NaN,None,None,None,None,None,2014.0
102,1612590108803,62805010724,2014-06-30,2005-08-17,94605-1614,None,Elementary Schools (Public),Elementary,K-12,37.774289,...,12.00,None,24.18,23.50,None,None,None,None,None,2014.0
105,1612590109983,62805010728,2014-06-30,2005-08-29,94601-2455,None,Elementary Schools (Public),Elementary,K-5,37.782892,...,22.66,None,20.21,20.96,None,None,None,None,None,2014.0
118,1612590125856,62805013190,2014-10-28,2012-08-06,94607-1404,None,K-12 Schools (Public),Elementary,K-12,37.745418,...,NaN,None,17.40,NaN,None,None,None,None,None,2014.0
130,1612590131946,62805013889,2016-06-30,2015-08-31,94605-4000,Directly funded,Intermediate/Middle Schools (Public),Elementary,6-8,37.758313,...,NaN,None,NaN,NaN,None,None,None,None,None,2016.0
135,1612596117394,62805007941,2014-06-30,1999-09-07,94605-3553,Directly funded,Elementary Schools (Public),Elementary,K-8,37.760967,...,20.00,None,17.61,17.95,None,None,None,None,None,2014.0
143,16638750121491,60318012713,2015-06-30,2010-08-23,92083-7736,Directly funded,K-12 Schools (Public),High School,K-12,33.170564,...,11.95,None,25.33,20.00,None,None,None,None,None,2015.0
144,16638910120154,60969012489,2014-06-30,2009-08-19,92660,Directly funded,K-12 Schools (Public),High School,K-12,33.659935,...,2.67,None,31.78,22.47,None,None,None,None,None,2014.0
164,19101990109918,69107810894,2014-06-30,2005-09-06,90037,Directly funded,High Schools (Public),High School,9-12,33.996155,...,8.00,None,18.50,20.75,None,None,None,None,None,2014.0
167,19101990112730,69107811974,2015-05-29,2006-09-12,90001-3633,Directly funded,Elementary Schools (Public),Elementary,K-5,33.959940,...,24.00,None,24.86,20.33,None,None,None,None,None,2015.0
187,19646000120543,61704012461,2014-06-30,2009-09-25,90250,Directly funded,High Schools (Public),High School,7-12,33.908480,...,42.24,None,12.41,19.01,None,None,None,None,None,2014.0
188,19646000120550,61704012508,2014-06-30,2009-09-25,91405,Directly funded,High Schools (Public),High School,7-12,34.191519,...,14.64,None,6.06,22.06,None,None,None,None,None,2014.0
207,19647256118269,62250008507,2015-06-30,2000-08-01,90813-1929,Directly funded,Elementary Schools (Public),Elementary,K-8,33.788129,...,22.90,None,27.06,21.92,None,None,None,None,None,2015.0
213,19647330100768,62271011353,2013-06-30,2003-09-08,90016,Directly funded,Elementary Schools (Public),Elementary,K-8,34.018209,...,14.33,None,16.24,25.54,None,None,None,None,None,2013.0
243,19647330109553,62271010890,2015-06-30,2005-09-07,90041-2547,Directly funded,High Schools (Public),High School,9-12,34.137422,...,17.00,None,18.98,17.24,None,None,None,None,None,2015.0
244,19647330109876,62271010892,2014-06-30,2005-09-06,91342,None,High Schools (Public),High School,9-12,34.279435,...,25.20,None,17.74,17.78,None,None,None,None,None,2014.0
264,19647330112433,62271011664,2015-06-30,2006-09-06,90018-1832,Directly funded,Intermediate/Middle Schools (Public),Intermediate/Middle/Junior High,6-8,34.032630,...,9.00,None,32.93,34.56,None,None,None,None,None,2015.0
266,19647330112557,62271011667,2015-06-30,2006-09-06,90018-1832,Directly funded,High Schools (Public),High School,9-12,34.032630,...,12.00,None,36.50,36.67,None,None,None,None,None,2015.0
297,19647330117960,62271012205,2015-06-30,2008-08-13,90255-3006,Directly funded,Elementary Schools (Public),Elementary,K-6,33.987036,...,9.00,None,26.11,25.56,None,None,None,None,None,2015.0
313,19647330121277,62271012573,2015-06-30,2010-08-30,90043-4420,Directly funded,Intermediate/Middle Schools (Public),Intermediate/Middle/Junior High,6-8,33.976373,...,11.00,None,29.60,26.55,None,None,None,None,None,2015.0
324,19647330122598,62271012812,2015-06-30,2010-08-30,91352-1844,Directly funded,High Schools (Public),High School,9-12,34.234825,...,12.00,None,12.29,14.42,None,None,None,None,None,2015.0
334,19647330122762,62271012699,2015-06-30,2010-09-13,90017-3837,Directly funded,High Schools (Public),High School,9-12,34.048788,...,7.10,None,18.61,19.15,None,None,None,None,None,2015.0
378,19647330127951,62271013390,2014-06-30,2013-08-13,90016,Directly funded,Intermediate/Middle Schools (Public),Intermediate/Middle/Junior High,6-8,34.022330,...,NaN,None,NaN,NaN,None,None,None,None,None,2014.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
654,33671570120279,62778012445,2014-07-25,2009-09-14,92590,Directly funded,K-12 Schools (Public),Elementary-High Combination,K-12,33.501427,...,18.45,None,15.73,22.76,None,None,None,None,None,2014.0
666,33751760124859,60002712914,2015-06-30,2011-08-10,92530-2809,Locally funded,K-12 Schools (Public),Elementary-High Combination,K-12,33.682028,...,12.20,None,23.76,27.13,None,None,None,None,None,2015.0
740,36678760122572,63417012727,2014-07-30,2010-09-07,92410,Directly funded,K-12 Schools (Public),Elementary-High Combination,K-12,34.102751,...,14.50,None,25.34,31.52,None,None,None,None,None,2014.0
757,36750773630837,60001707296,2002-10-24,1997-08-04,92307,Directly funded,Alternative Schools of Choice,Elementary-High Combination,K-12,NaN,...,61.75,None,21.78,22.19,None,None,None,None,None,2002.0
760,37679670128595,60210013668,2015-06-30,2013-08-19,92117-5937,Directly funded,K-12 Schools (Public),Elementary,K-12,32.803780,...,NaN,None,NaN,NaN,None,None,None,None,None,2015.0
773,37680310126110,60987013204,2015-06-30,2013-08-20,92118-1714,Directly funded,K-12 Schools (Public),High School,K-12,32.692605,...,NaN,None,NaN,NaN,None,None,None,None,None,2015.0
791,37681630130815,61914013824,2015-07-16,2014-08-08,91950-7715,Directly funded,Elementary Schools (Public),Elementary,K-8,32.667861,...,NaN,None,NaN,NaN,None,None,None,None,None,2015.0
796,37682130119263,62610012418,2014-06-30,2009-09-08,92660,Directly funded,High Schools (Public),Elementary-High Combination,6-12,33.659935,...,8.64,None,33.86,27.78,None,None,None,None,None,2014.0
826,37683380121178,63432012577,2014-01-31,2010-09-06,92102,Directly funded,High Schools (Public),High School,9-12,32.713015,...,6.15,None,24.50,14.63,None,None,None,None,None,2014.0
866,37684370101220,64071011398,2015-06-18,2004-08-30,92028-9795,Directly funded,K-12 Schools (Public),Elementary-High Combination,K-12,33.413867,...,7.50,None,25.07,20.80,None,None,None,None,None,2015.0
902,39103970114447,69103111968,2014-06-30,2007-08-20,95206-3950,None,High Schools (Public),High School,7-12,37.907744,...,6.25,None,21.29,27.36,None,None,None,None,None,2014.0
920,39686270129361,62703013784,2015-03-16,2014-09-02,95202,Directly funded,K-12 Schools (Public),Elementary-High Combination,K-12,37.953471,...,NaN,None,NaN,NaN,None,None,None,None,None,2015.0
925,39686270132035,62703013921,2016-07-01,2016-07-01,95207-6216,Directly funded,K-12 Schools (Public),Elementary-High Combination,K-12,37.990127,...,NaN,None,NaN,NaN,None,None,None,None,None,2016.0
945,39754990120519,60004712453,2014-06-30,2009-09-08,92660,Directly funded,K-12 Schools (Public),Elementary-High Combination,K-12,33.659935,...,4.61,None,33.96,24.95,None,None,None,None,None,2014.0
966,41690620118232,63639012231,2014-06-30,2008-07-31,94303-1311,None,High Schools (Public),High School,9-12,37.467418,...,12.50,None,17.43,14.64,None,None,None,None,None,2014.0
971,42691120127704,60528013441,2014-06-30,2013-07-01,93105,None,K-12 Schools (Public),High School,K-12,34.440705,...,NaN,None,NaN,NaN,None,None,None,None,None,2014.0
974,42692454230199,62292010662,2015-06-30,2001-11-13,93441,Directly funded,K-12 Schools (Public),Elementary-High Combination,K-12,34.665479,...,27.10,None,15.76,11.14,None,None,None,None,None,2015.0
995,43104390126045,69103513200,2014-08-15,2014-08-15,94301,Directly funded,Elementary Schools (Public),Elementary,K-3,37.446862,...,NaN,None,NaN,NaN,None,None,None,None,None,2014.0
999,43104390129262,69103513747,2014-08-19,2014-08-19,95116,Directly funded,Elementary Schools (Public),Elementary,K-5,37.357607,...,NaN,None,NaN,NaN,None,None,None,None,None,2014.0
1140,49709200125773,63583013137,2014-08-13,2014-08-13,95401,Locally funded,High Schools (Public),High School,9-12,38.451309,...,NaN,None,NaN,NaN,None,None,None,None,None,2014.0
1161,50710680121574,61104012826,2015-06-30,2010-08-16,95316,Locally funded,Elementary Schools (Public),Elementary,K-5,NaN,...,7.50,None,20.80,21.20,None,None,None,None,None,2015.0
1186,51714566053334,64290006984,None,1980-07-01,95957-9647,Directly funded,Elementary Schools (Public),Elementary,K-8,39.063424,...,3.00,None,13.50,8.33,None,None,None,None,None,nan
1189,52105205230073,69104310443,2014-06-30,2001-08-20,96080-2694,Directly funded,High Schools (Public),Elementary-High Combination,6-12,40.184171,...,5.00,None,13.56,13.60,None,None,None,None,None,2014.0
1193,53716620125757,60651013160,2012-09-04,2012-09-04,95527,Directly funded,K-12 Schools (Public),Elementary-High Combination,K-12,40.809908,...,NaN,None,NaN,NaN,None,None,None,None,None,2012.0
1202,54721166054340,63636006193,None,1980-07-01,93244,Locally funded,Elemen Schools In 1 School Dist. (Public),Elementary,K-7,36.375500,...,15.00,None,21.57,22.27,None,None,None,None,None,nan
1219,56105610127993,69104713266,2013-08-19,2013-08-19,91320,Directly funded,High Schools (Public),Elementary-High Combination,6-12,34.198088,...,NaN,None,NaN,NaN,None,None,None,None,None,2013.0
1230,57105790124305,69104912919,2014-06-30,2011-09-06,95695,Directly funded,High Schools (Public),High School,9-12,38.668294,...,NaN,None,48.93,NaN,None,None,None,None,None,2014.0
1248,7616480119586,60285012407,2014-06-30,2009-08-24,94531,Directly funded,Elementary Schools (Public),Elementary,K-9,37.969840,...,6.10,None,33.66,25.41,None,None,None,None,None,2014.0
1261,8100820109777,69106311577,2014-12-19,2005-09-19,95531,Directly funded,High Schools (Public),Elementary-High Combination,K-12,41.772906,...,2.50,None,23.20,11.60,None,None,None,None,None,2014.0
1264,9100900111716,69100611579,2013-07-01,2006-09-05,95667-8984,None,District Community Day Schools,Elementary,K-6,38.720320,...,1.00,None,5.00,11.00,None,None,None,None,None,2013.0